language: php
php:
  - 7.0
  - 7.1
addons:
  firefox: latest-nightly
  apt:
    packages:
      - google-chrome-stable
before_install:
  # Setup xvfb for Selenium
  # Xvfb: X virtual frame buffer is X11 server which does graphical operation in
  # memory, hence no output is displayed.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  # Start PhantomJS webdriver
  - phantomjs --webdriver=4445 > /dev/null &

  # dump the current versions
  - google-chrome-stable --version
  # Start Chrome headless
  - google-chrome-stable --no-sandbox --no-first-run --disable-extensions --disable-gpu --headless --remote-debugging-port=9222 about:blank &>/dev/null &
  #- while ! curl http://localhost:9222 &>/dev/null; do sleep 1; done

  # Download Chromedrive
  - wget http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - unzip -o -q chromedriver_linux64.zip

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar zxfv geckodriver-v0.23.0-linux64.tar.gz
  - chmod +x geckodriver

  # Get and run Selenium/
  - wget http://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar
         -O selenium-server-standalone.jar
  - java -Dwebdriver.chrome.driver=`pwd`/chromedriver
         -Dwebdriver.gecko.driver=`pwd`/geckodriver
         -jar selenium-server-standalone.jar > /dev/null 2>&1 &

  # Run composer install
  - composer install
script:
  - vendor/bin/behat -c behatGoutte.yml -s web features/web/exemploGoutte.feature
  - vendor/bin/behat -c behatChromeHeadless.yml -s web features/web/exemploJavaScript.feature
  - vendor/bin/behat -c behatChrome.yml -s web features/web/exemploJavaScript.feature
  - vendor/bin/behat -c behatFirefox.yml -s web features/web/exemploJavaScript.feature
  - vendor/bin/behat -c behatPhantomJS.yml -s web features/web/exemploJavaScript.feature
